#!/usr/bin/env python3
"""Generate daily market analysis signal for scheduler stock selection.

Writes data/market_analysis_signal.json with preferred_symbols and summary.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover
    def load_dotenv() -> bool:
        return False


def _market_bias_from_scores(scores: list[float]) -> tuple[str, float]:
    if not scores:
        return "DEFENSIVE", 0.25
    avg = sum(scores) / float(len(scores))
    # Convert typical 0-100 score band into confidence-like 0-1.
    confidence = max(0.2, min(0.95, avg / 100.0))
    if avg >= 72:
        return "AGGRESSIVE", confidence
    if avg >= 55:
        return "BALANCED", confidence
    return "DEFENSIVE", confidence


def main() -> int:
    load_dotenv()

    repo_root = Path(__file__).resolve().parents[1]
    src_dir = repo_root / "src"

    import sys

    if str(src_dir) not in sys.path:
        sys.path.insert(0, str(src_dir))

    from intraday_stock_selector import get_best_scalping_stocks  # pylint: disable=import-error

    top_n = 5
    candidates = get_best_scalping_stocks(limit=top_n)

    preferred_symbols = [str(row.get("symbol", "")).strip() for row in candidates if str(row.get("symbol", "")).strip()]
    scores = [float(row.get("score", 0.0)) for row in candidates]
    market_bias, confidence = _market_bias_from_scores(scores)

    if preferred_symbols:
        summary = (
            f"Top {len(preferred_symbols)} symbols selected from intraday liquidity/volatility analysis. "
            f"Bias={market_bias}, avg_score={sum(scores)/len(scores):.1f}."
        )
    else:
        summary = "No high-conviction symbols from intraday analysis; keep defensive posture."

    payload = {
        "generated_at": datetime.now(ZoneInfo("Asia/Seoul")).isoformat(),
        "summary": summary,
        "preferred_symbols": preferred_symbols,
        "watchlist_symbols": [],
        "excluded_symbols": [],
        "market_bias": market_bias,
        "confidence": round(confidence, 2),
        "notes": "Auto-generated by scripts/market_analysis_runner.py",
    }

    output_path = repo_root / "data" / "market_analysis_signal.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"[market-analysis] wrote {output_path}")
    print(f"[market-analysis] preferred_symbols={','.join(preferred_symbols) if preferred_symbols else '-'}")
    print(f"[market-analysis] bias={market_bias} confidence={payload['confidence']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
